"use client";

import Link from "next/link";
import { type ChangeEvent, type FormEvent, useEffect, useState } from "react";
import { useRouter } from "next/navigation";
import {
  defaultPracticePlan,
  loadPracticePlan,
  practiceFocusLabels,
  savePracticePlan,
  type PracticeFocus,
  type PracticePlan,
  type FollowUpDepth,
  type InterruptionFrequency,
  type InterviewerStyle,
  type PressureLevel,
  type VoiceProviderId,
  voiceProviderLabels,
} from "../interview/practicePlan";

export default function SetupPage() {
  const router = useRouter();
  const [plan, setPlan] = useState<PracticePlan>(defaultPracticePlan);
  const [isPlanning, setIsPlanning] = useState(false);
  const [planningError, setPlanningError] = useState<string | null>(null);
  const [planningSource, setPlanningSource] = useState<"provider" | "fallback" | null>(null);

  useEffect(() => {
    setPlan(loadPracticePlan());
  }, []);

  function submitSetup(event: FormEvent<HTMLFormElement>) {
    event.preventDefault();
    try {
      savePracticePlan({
        ...plan,
        targetRole: plan.targetRole.trim() || defaultPracticePlan.targetRole,
        topics: plan.topics.trim(),
      });
      router.push("/interview");
    } catch {
      setPlanningError("Could not save setup in this browser. Clear local site data and try again.");
    }
  }

  function importQuestions(event: ChangeEvent<HTMLInputElement>) {
    const file = event.target.files?.[0];
    if (!file) return;
    if (file.size > 20_000) {
      setPlanningError("Question files must be 20 KB or smaller.");
      event.target.value = "";
      return;
    }
    void file.text().then((text) => {
      setPlanningError(null);
      setPlan((current) => ({ ...current, questionBank: text, plannedQuestions: [] }));
    }).catch(() => setPlanningError("Could not read that question file."));
  }

  async function generatePlan() {
    setIsPlanning(true);
    setPlanningError(null);
    try {
      const baseUrl = process.env.NEXT_PUBLIC_API_BASE_URL ?? "http://127.0.0.1:8000";
      const response = await fetch(`${baseUrl}/interview/plan`, {
        method: "POST",
        headers: { "Content-Type": "application/json" },
        body: JSON.stringify({
          target_role: plan.targetRole,
          practice_focus: plan.focus,
          practice_topics: plan.topics,
          question_bank: plan.questionBank,
          total_duration_seconds: plan.directorSettings.totalDurationMinutes * 60,
        }),
      });
      if (!response.ok) throw new Error("Planning failed");
      const result = await response.json() as { provider: "provider" | "fallback"; questions: PracticePlan["plannedQuestions"] };
      if (!result.questions.length) throw new Error("Planning returned no questions");
      setPlan((current) => ({ ...current, plannedQuestions: result.questions }));
      setPlanningSource(result.provider);
    } catch {
      setPlanningError("Could not generate a plan. Check that the Python backend is running.");
    } finally {
      setIsPlanning(false);
    }
  }

  return (
    <main className="page-shell">
      <nav className="topbar" aria-label="Setup navigation">
        <Link href="/">AI Interview Simulator</Link>
        <Link href="/reports">Interview history</Link>
        <Link href="/settings">API settings</Link>
      </nav>

      <section className="setup-layout">
        <div className="setup-copy">
          <p className="eyebrow">Session setup</p>
          <h1>Prepare the room before the interviewer joins.</h1>
          <p>
            Choose the role and interview tone before entering the room.
          </p>
          <section className="answer-summary" aria-live="polite">
            <h2>Interview plan preview</h2>
            {plan.plannedQuestions.length ? plan.plannedQuestions.map((question, index) => (
              <article key={question.id}>
                <strong>{index + 1}. ~{Math.max(1, Math.round(question.allocated_seconds / 60))} min · {question.focus}</strong>
                <p>{question.prompt}</p>
              </article>
            )) : <p>Generate a plan to preview the actual questions and time allocation before entering the room.</p>}
            {plan.plannedQuestions.length && planningSource ? (
              <p className="input-hint">
                {planningSource === "provider" ? "Generated by the configured planning provider." : "Planning provider unavailable; using the deterministic local fallback."}
              </p>
            ) : null}
          </section>
        </div>

        <form className="setup-form" onSubmit={submitSetup}>
          <label>
            Target role
            <input
              name="role"
              onChange={(event) =>
                setPlan((current) => ({
                  ...current,
                  targetRole: event.target.value,
                  plannedQuestions: [],
                }))
              }
              placeholder="Software Engineering Intern"
              value={plan.targetRole}
            />
          </label>

          <label>
            Today's practice focus
            <select
              name="focus"
              onChange={(event) =>
                setPlan((current) => ({
                  ...current,
                  focus: event.target.value as PracticeFocus,
                  plannedQuestions: [],
                }))
              }
              value={plan.focus}
            >
              {Object.entries(practiceFocusLabels).map(([value, label]) => (
                <option key={value} value={value}>
                  {label}
                </option>
              ))}
            </select>
          </label>

          <label>
            Live interviewer model
            <select
              onChange={(event) =>
                setPlan((current) => ({
                  ...current,
                  voiceProvider: event.target.value as VoiceProviderId,
                }))
              }
              value={plan.voiceProvider}
            >
              <option value="openai">{voiceProviderLabels.openai}</option>
              <option value="google">{voiceProviderLabels.google}</option>
            </select>
          </label>

          <fieldset className="director-setup-panel">
            <legend>Director settings</legend>
            <p>
              Configure the room before the interview. These controls lock when
              the session starts.
            </p>
            <div className="director-setup-grid">
              <label>
                Interviewer style
                <select
                  onChange={(event) =>
                    setPlan((current) => ({
                      ...current,
                      directorSettings: {
                        ...current.directorSettings,
                        interviewerStyle: event.target.value as InterviewerStyle,
                      },
                    }))
                  }
                  value={plan.directorSettings.interviewerStyle}
                >
                  <option value="friendly">Friendly</option>
                  <option value="professional">Professional</option>
                  <option value="strict">Strict</option>
                </select>
              </label>
              <label>
                Initial pressure
                <select
                  onChange={(event) =>
                    setPlan((current) => ({
                      ...current,
                      directorSettings: {
                        ...current.directorSettings,
                        initialPressure: event.target.value as PressureLevel,
                      },
                    }))
                  }
                  value={plan.directorSettings.initialPressure}
                >
                  <option value="low">Low</option>
                  <option value="medium">Medium</option>
                  <option value="high">High</option>
                </select>
              </label>
              <label>
                Follow-up depth
                <select
                  onChange={(event) =>
                    setPlan((current) => ({
                      ...current,
                      directorSettings: {
                        ...current.directorSettings,
                        followUpDepth: event.target.value as FollowUpDepth,
                      },
                    }))
                  }
                  value={plan.directorSettings.followUpDepth}
                >
                  <option value="light">Light</option>
                  <option value="standard">Standard</option>
                  <option value="deep">Deep</option>
                </select>
              </label>
              <label>
                Challenge frequency
                <select
                  onChange={(event) =>
                    setPlan((current) => ({
                      ...current,
                      directorSettings: {
                        ...current.directorSettings,
                        interruptionFrequency: event.target
                          .value as InterruptionFrequency,
                      },
                    }))
                  }
                  value={plan.directorSettings.interruptionFrequency}
                >
                  <option value="low">Low</option>
                  <option value="medium">Medium</option>
                  <option value="high">High</option>
                </select>
              </label>
            </div>
          </fieldset>

          <label>
            Questions or topics for today
            <textarea
              name="topics"
              onChange={(event) =>
                setPlan((current) => ({ ...current, topics: event.target.value, plannedQuestions: [] }))
              }
              placeholder="Examples: Explain the architecture of my project. Ask me about binary search. Practise a UCL internship behavioural question."
              rows={5}
              value={plan.topics}
            />
          </label>

          <label>
            Reference interview duration
            <select
              onChange={(event) =>
                setPlan((current) => ({
                  ...current,
                  directorSettings: {
                    ...current.directorSettings,
                    totalDurationMinutes: Number(event.target.value) as 10 | 15 | 20 | 30,
                  },
                  plannedQuestions: [],
                }))
              }
              value={plan.directorSettings.totalDurationMinutes}
            >
              <option value={10}>10 minutes</option>
              <option value={15}>15 minutes</option>
              <option value={20}>20 minutes</option>
              <option value={30}>30 minutes</option>
            </select>
            <span className="input-hint">A flexible reference. The interviewer may shorten, extend, or skip lower-value questions when it serves the interview.</span>
          </label>

          <label className="checkbox-row">
            <input
              checked={plan.allowAiWhiteboardAnnotations}
              onChange={(event) =>
                setPlan((current) => ({
                  ...current,
                  allowAiWhiteboardAnnotations: event.target.checked,
                }))
              }
              type="checkbox"
            />
            <span>
              Allow reviewed AI whiteboard annotations
              <small>Questions are still shown on the board. Turn this off to prevent automatic circles, lines, arrows, highlights, and notes.</small>
            </span>
          </label>

          <label>
            Upload interview questions / past questions
            <input
              accept=".txt,.md,.csv,text/plain,text/markdown,text/csv"
              onChange={importQuestions}
              type="file"
            />
            <span className="input-hint">
              {plan.questionBank.trim()
                ? `Loaded: ${plan.questionBank.split(/\r?\n/).filter(Boolean).length} lines. This file will be the question plan for this interview.`
                : "Optional. Use one question per line; uploaded questions take priority for this interview."}
            </span>
          </label>

          <p className="setup-note">
            Manage live interviewer API keys in <Link href="/settings">Settings</Link>. The planning provider is configured in the project environment.
          </p>

          <button className="secondary-action full-width" disabled={isPlanning} onClick={() => void generatePlan()} type="button">
            {isPlanning ? "Generating plan…" : "Generate interview plan"}
          </button>
          {planningError ? <p className="error-message">{planningError}</p> : null}

          <button className="primary-action full-width" type="submit">
            Enter waiting room
          </button>
        </form>
      </section>
    </main>
  );
}
